# This is a basic workflow to help you get started with Actions

name: Bintray Upload

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gradle:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: bintrayUpload -PdryRun=false
      env:
        BINTRAY_USER: yatsinar
        BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }} 

