name: "core: publish (bintray)"

on:
  push:
    tags:
      - 'core*'

jobs:
  publish-bintray:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: :core:bintrayUpload -PdryRun=false
        env:
          BINTRAY_USER: yatsinar
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}