name: "core: publish (maven)"

on:
  release:
    types: [published]

jobs:
  publish-bintray:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/core')

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      #Decode key ring file from secrets and put it to ~/.gradle/
      - name: Decode
        run: |
          echo "${{secrets.SECRET_KEY_RING_FILE}}" > ~/.gradle/secring.gpg.b64
          base64 -d ~/.gradle/secring.gpg.b64 > ~/.gradle/secring.gpg
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: :core:uploadArchives -Psigning.keyId=${{secrets.SIGNING_KEY_ID}} -Psigning.password=${{ secrets.SIGNING_PASSWORD }} -Psigning.secretKeyRingFile=$(echo ~/.gradle/secring.gpg)
        env:
          ORG_GRADLE_PROJECT_mavenCentralRepositoryUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralRepositoryPassword: ${{ secrets.OSSRH_PASSWORD }}
